# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 16:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ranger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='parameters_definition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text='A list of strings which are the parameters for this role.', size=None),
        ),
    ]
